# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-28 10:34
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_time', models.DateField(default=datetime.datetime.now, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('pub_content', models.TextField(verbose_name='\u901a\u77e5\u8be6\u60c5')),
                ('pub_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u53d1\u5e03\u4eba')),
            ],
            options={
                'verbose_name': '\u901a\u77e5\u53d1\u5e03',
                'verbose_name_plural': '\u901a\u77e5\u53d1\u5e03',
            },
        ),
        migrations.CreateModel(
            name='UserAnswerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='\u7528\u6237\u7b54\u6848')),
                ('score', models.IntegerField(verbose_name='\u5f97\u5206')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='\u4f5c\u7b54\u65f6\u95f4')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coures.CourseList', verbose_name='\u8bfe\u7a0b')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coures.Paper', verbose_name='\u8bd5\u5377')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u505a\u9898\u8bb0\u5f55',
                'verbose_name_plural': '\u7528\u6237\u505a\u9898\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='\u7559\u8a00\u65f6\u95f4')),
                ('note_content', models.TextField(default='', verbose_name='\u7559\u8a00\u5185\u5bb9')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7559\u8a00\u4eba')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u7559\u8a00',
                'verbose_name_plural': '\u7528\u6237\u7559\u8a00',
            },
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0, verbose_name='\u603b\u5206')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='\u5f55\u5165\u65f6\u95f4')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coures.Paper', verbose_name='\u8bd5\u5377')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u603b\u5206',
                'verbose_name_plural': '\u7528\u6237\u603b\u5206',
            },
        ),
    ]
