# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-03 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('operate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscore',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coures.PaperList',
                                    verbose_name='\u8bd5\u5377'),
        ),
    ]
