# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-03 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, verbose_name='\u5b66\u53f7')),
            ],
            options={
                'verbose_name': '\u5141\u8bb8\u5b66\u53f7',
                'verbose_name_plural': '\u5141\u8bb8\u5b66\u53f7',
            },
        ),
    ]
